### PR TITLE
NERSC: add a few more packages already installed on Cori as RPMs

### PR DESCRIPTION
**Pull request by bcfriesen**

### CODE REVIEW

**Comment by bcfriesen** [comment]
Hi @ax3l,

> Wouldn't it be useful to specify the system compiler for those versions as well, for optimal compatibility?

When you say 'the system compiler for those versions', do you mean 'the compiler used to compile each RPM'? As far as I can tell, the RPM metadata does not contain that information, e.g.,

```console
user@cori07:~> rpm -qi binutils
Name        : binutils
Version     : 2.31
Release     : 9.26.1
Architecture: x86_64
Install Date: Wed Apr 10 09:15:32 2019
Group       : Development/Tools/Building
Size        : 46298732
License     : GFDL-1.3-only AND GPL-3.0-or-later
Signature   : RSA/SHA256, Wed Sep  5 05:10:31 2018, Key ID 70af9e8139db7c82
Source RPM  : binutils-2.31-9.26.1.src.rpm
Build Date  : Wed Sep  5 05:06:54 2018
Build Host  : sheep10
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : http://www.gnu.org/software/binutils/
Summary     : GNU Binutils
Description :
C compiler utilities: ar, as, gprof, ld, nm, objcopy, objdump, ranlib,
size, strings, and strip. These utilities are needed whenever you want
to compile a program or kernel.
Distribution: SUSE Linux Enterprise 12
```

**Comment by ax3l** [comment]
> Do you mean 'the compiler used to compile each RPM'?

Yes, that is what I thought of. You can just specify the external packages further by appending `%gcc@4.8` after the version.

As with other binary distributions (e.g. in Debian), the default system compiler is used to build official RPMs which are the binary artifacts you point to. In SUSE Linux Enterprise 12, this compiler is GCC 4.8, as far as I can see:

https://www.suse.com/media/presentation/FUT92712_build_faster_applications_toolchain_roadmap.pdf
https://software.opensuse.org/package/gcc

**Comment by bcfriesen** [comment]
@ax3l - thanks for the tip! I added `%gcc@4.8.5` (obtained by `/usr/bin/gcc --version`) to each RPM package installed in `/usr`.

**Comment by ax3l** [comment]
Looks good to me! :)

**Comment by mamelara** [comment]
Won't this create rebuilds since we're going to be using later versions of gcc for our builds? I'll have to test after the Cori maintenance.

**Comment by ax3l** [comment]
Yes, this will rebuild with different GCC chains, but will also guarantee you optimal compatibility.

**Comment by mamelara** [comment]
Hmmm...yeah I believe we wanted to cut down on the rebuilds...

**Comment by bcfriesen** [comment]
Right, there is no point to having this `packages.yaml` file at all if adding the `%gcc@4.8.5` causes all of these packages to be rebuilt. (I should have tested this before making the change.) Almost nobody uses the system GCC to build anything. Before adding the `%gcc@4.8.5` part, I tested this `packages.yaml` with several different spack builds of several different packages and several different compilers and never had any compatibility problems.

**Comment by mamelara** [comment]
@bcfriesen can we also rename `cori_and_edison` to`cori` or maybe something more generic. I think we might keep the CrayPEs across Cori and Perlmutter consistent?

**Comment by bcfriesen** [comment]
Yes I was thinking about this too; it should be done in a separate PR though IMO.

I will make a GH 'issue' to track this.

**Comment by ax3l** [comment]
For tools such as `cmake` you can definitely do this and skip the compilers, overlooked that in the last change.
I would be more careful with libs, especially C++ ones. But the list looks like mainly C-dominated.

**Comment by bcfriesen** [comment]
@mamelara the addition of `%gcc@4.8.5` to the system packages in `/usr` does not appear to trigger many more rebuilds in a few tests I did. So I think this is OK to merge.

**Pull request merged**
