### PR TITLE
Addding compilers and packages for titan.

### PR DESCRIPTION
**Pull request by khuck**
not fully tested, but a good start

### CODE REVIEW

**Comment by tgamblin** [comment]
@mpbelhorn: can you or somebody at ORNL take a look at this one?

**Comment by mpbelhorn** [comment]
@tgamblin : I've only had a chance to take a cursory look at this but will do a more thorough comparison to what's on Titan on Monday; I'm in the middle of moving apartments this weekend.

@khuck : I suspect that you constructed these configs from the CrayPE modules actually on Titan via access to Titan. Can you confirm if that's the case? This looks really promising.

And as a general FYI, we have spack configs for each of our machines already in version control. This has a much more complete `packages.yaml` for the Crays than what we currently use. We've been focusing on deploying software with spack on our IBM machines and haven't been using Spack all that much on Titan/Eos. The git repo with our configs is not public, but can be reached with access to the OLCF filesystem at `/sw/titan/.swci/1-compute/etc/nccs-sw-ci/*/*/spack/*.yaml`. The various `${HOST}/[0-1]-(compute|login|core|*)` directories are for spack instances that separately target either

- `0-*`:  the login-nodes, base OS compiler, and MPI-less user tools, packages that PGI/XL compilers choke on.
- `1-*`: the compute nodes or builds that depend on MPI or Programming environments.

Having these builds separated in different spack instances was a work-around for issues in early (pre-v0.8) spack before a single instance of spack could keep track of configs separated by OS and platform.

If you (@khuck ) have access to Titan, see for instance `/sw/titan/.swci/1-compute/etc/spack/*.yaml`. For `compilers.yaml`, we've found in the past that it's been necessary to use the full path to the Cray compiler wrappers: I'm not sure if that's still the case and we should check if that's still the case.

When I get a chance on Monday, I'll diff this against what we currently use and will post the configs for summit.olcf.ornl.gov, titan.ccs.ornl.gov, eos.css.ornl.gov, ascent.olcf.ornl.gov, dtn.ccs.ornl.gov and the other public machines.

**Comment by khuck** [comment]
@mpbelhorn Thanks for looking into these! Yes, I made these on Titan, using the ```spack compiler find``` and using the NERSC Cray packages.yaml as a starting point, then updating the paths to modules and versions accordingly. 

I didn't know there were files like these in version control at ORNL, I suppose I should have asked first. :) At the ECP meeting in January I asked the Spack team about getting access to Titan-specific configurations and they suggested it was a crowd-sourced effort and that I was welcome to make my own and submit them - so I did. :)

I am glad you're using Spack on summit, I wasn't looking forward to figuring that one out yet - I have much more experience with the idiosyncrasies of Titan/Jaguar.  I am happy to defer to the OLCF experts with respect to these configurations!

Thanks again!

**Comment by tgamblin** [comment]
Titan is retired.  Sorry we didn't get to this ☹️

**Comment by khuck** [comment]
Eh, it was a worthwhile exercise regardless. It helped me with summit, for what it’s worth. Thanks!

**Pull request closed without merging**
